import { useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import {
    ArrowLeft,
    Code2,
    Layout,
    Type,
    Square,
    MousePointer2,
    Copy,
    Check,
    Download,
    Terminal,
    Layers,
    Settings2,
    Monitor,
    Smartphone,
    Tablet,
    Eye,
    Trash2
} from 'lucide-react';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

const translations = {
    en: {
        back: "Back to Hub",
        title: "Design-to-Code Builder",
        components: "Components",
        layers: "Layers",
        emptyCanvas: "Empty Canvas",
        selectComponent: "Select a component from the left",
        realTime: "Real-time preview",
        generatedCode: "Generated Code (React)",
        properties: "Properties",
        labelText: "Label / Text",
        instantFeedback: "Changes are reflected instantly in the code on the right.",
        selectToEdit: "Select an element on the canvas to edit.",
        copyCode: "COPY CODE",
        copied: "COPIED",
        elementLabels: {
            button: 'Button',
            input: 'Input',
            card: 'Card',
            text: 'Text'
        }
    },
    fr: {
        back: "Retour au Hub",
        title: "Builder Design-to-Code",
        components: "Composants",
        layers: "Couches",
        emptyCanvas: "Canevas Vide",
        selectComponent: "Sélectionnez un composant à gauche",
        realTime: "Aperçu en temps réel",
        generatedCode: "Code Généré (React)",
        properties: "Propriétés",
        labelText: "Label / Texte",
        instantFeedback: "Les changements sont reflétés instantanément dans le code à droite.",
        selectToEdit: "Sélectionnez un élément sur le canevas pour l'éditer.",
        copyCode: "COPIER LE CODE",
        copied: "COPIÉ",
        elementLabels: {
            button: 'Bouton',
            input: 'Entrée',
            card: 'Carte',
            text: 'Texte'
        }
    }
};

interface Element {
    id: string;
    type: 'button' | 'input' | 'card' | 'text';
    label: string;
}

const SESSION_PREFIX = Math.floor(Math.random() * 1000000);

export default function BuilderApp() {
    const navigate = useNavigate();
    const [lang] = useState<'en' | 'fr'>(() => {
        return (localStorage.getItem('app_lang') as 'en' | 'fr') || 'en';
    });
    const t = translations[lang];

    const [elements, setElements] = useState<Element[]>([]);
    const [selectedId, setSelectedId] = useState<string | null>(null);
    const idCounter = useRef(0);
    const [copied, setCopied] = useState(false);
    const [previewMode, setPreviewMode] = useState<'desktop' | 'tablet' | 'mobile'>('desktop');

    const addElement = (elementType: Element['type']) => {
        idCounter.current += 1;
        const id = `el-${SESSION_PREFIX}-${idCounter.current}`;
        const newEl: Element = {
            id,
            type: elementType,
            label: t.elementLabels[elementType]
        };
        setElements([...elements, newEl]);
        setSelectedId(id);
    };

    const generateCode = () => {
        const components = elements.map(el => {
            if (el.type === 'button') return `      <button className="px-6 py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-xl font-bold transition-all shadow-lg shadow-purple-500/20">\n        ${el.label}\n      </button>`;
            if (el.type === 'input') return `      <input className="w-full bg-[#161618] border border-white/10 rounded-xl px-4 py-2 focus:border-purple-500 outline-none transition-all" placeholder="${el.label}..." />`;
            if (el.type === 'card') return `      <div className="bg-[#161618] p-6 rounded-3xl border border-white/5 shadow-xl">\n        <h3 className="font-bold mb-2">Card Title</h3>\n        <p className="text-sm text-gray-500">Design generated by Design-to-Code AI.</p>\n      </div>`;
            if (el.type === 'text') return `      <p className="text-gray-400 text-sm leading-relaxed">${el.label}</p>`;
            return '';
        }).join('\n\n');

        return `// Optimized React + Tailwind Code\nimport React from 'react';\n\nexport default function GeneratedComponent() {\n  return (\n    <div className="p-8 space-y-6 max-w-md mx-auto bg-[#0A0A0B] min-h-screen text-white">\n${components}\n    </div>\n  );\n}`;
    };

    const copyCode = () => {
        navigator.clipboard.writeText(generateCode());
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const triggerDownload = (blob: Blob, fileName: string) => {
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = fileName;
        link.style.display = 'none';
        link.target = '_blank';
        document.body.appendChild(link);
        link.click();
        setTimeout(() => {
            if (document.body.contains(link)) {
                document.body.removeChild(link);
            }
            URL.revokeObjectURL(url);
        }, 1500);
    };

    const handleDownload = (e: React.MouseEvent) => {
        e.preventDefault();
        e.stopPropagation();
        const code = generateCode();
        const blob = new Blob([code], { type: 'text/plain;charset=utf-8' });
        triggerDownload(blob, 'GeneratedComponent.tsx');
    };

    const cn = (...inputs: ClassValue[]) => twMerge(clsx(inputs));

    return (
        <div className="flex flex-col h-screen bg-[#0A0A0B] text-white">
            {/* Top Bar */}
            <header className="flex items-center justify-between px-6 py-4 bg-[#111113] border-b border-white/5 relative z-20">
                <div className="flex items-center gap-4">
                    <button
                        title={t.back}
                        onClick={() => navigate('/')}
                        className="p-2 hover:bg-white/5 rounded-xl transition-colors text-gray-400 hover:text-white"
                    >
                        <ArrowLeft size={20} />
                    </button>
                    <div className="flex items-center gap-3">
                        <div className="p-2 bg-purple-500/10 rounded-lg">
                            <Code2 className="text-purple-400 w-5 h-5" />
                        </div>
                        <h1 className="text-sm font-bold">{t.title}</h1>
                    </div>
                </div>

                <div className="flex items-center gap-2 bg-white/5 rounded-xl p-1 border border-white/5">
                    {[
                        { id: 'desktop', icon: Monitor },
                        { id: 'tablet', icon: Tablet },
                        { id: 'mobile', icon: Smartphone }
                    ].map(mode => (
                        <button
                            type="button"
                            key={mode.id}
                            title={mode.id}
                            onClick={() => setPreviewMode(mode.id as 'desktop' | 'tablet' | 'mobile')}
                            className={cn(
                                "p-2 rounded-lg transition-all",
                                previewMode === mode.id ? "bg-purple-600 text-white" : "text-gray-500 hover:text-white"
                            )}
                        >
                            <mode.icon size={16} />
                        </button>
                    ))}
                </div>

                <div className="flex items-center gap-3">
                    <button
                        type="button"
                        onClick={copyCode}
                        className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl transition-all font-bold text-xs text-gray-400 hover:text-white"
                        title={t.copyCode}
                    >
                        {copied ? <Check size={14} /> : <Copy size={14} />}
                        {copied ? t.copied : t.copyCode}
                    </button>
                    <button
                        type="button"
                        title="Download"
                        onClick={(e) => handleDownload(e)}
                        className="flex items-center gap-2 px-4 py-2 bg-purple-600 hover:bg-purple-700 rounded-xl transition-all font-bold text-xs"
                    >
                        <Download size={14} />
                    </button>
                </div>
            </header>

            <div className="flex-1 flex overflow-hidden">
                {/* Left Sidebar: Components */}
                <aside className="w-16 md:w-64 flex flex-col bg-[#0D0D0F] border-r border-white/5 p-4 py-8">
                    <h3 className="hidden md:block text-[10px] font-bold text-gray-600 uppercase tracking-widest mb-6 px-2">{t.components}</h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                        {[
                            { icon: Square, label: t.elementLabels.button, type: 'button' },
                            { icon: Type, label: t.elementLabels.input, type: 'input' },
                            { icon: Layout, label: t.elementLabels.card, type: 'card' },
                            { icon: Type, label: t.elementLabels.text, type: 'text' }
                        ].map((item) => (
                            <button
                                type="button"
                                key={item.label}
                                onClick={() => addElement(item.type as 'button' | 'input' | 'card' | 'text')}
                                className="flex flex-col items-center justify-center p-4 bg-white/[0.02] border border-white/5 rounded-2xl hover:border-purple-500/50 hover:bg-purple-500/[0.02] transition-all group"
                            >
                                <item.icon size={20} className="text-gray-500 group-hover:text-purple-400 mb-2" />
                                <span className="hidden md:block text-[10px] font-bold text-gray-500 group-hover:text-white uppercase tracking-tighter">{item.label}</span>
                            </button>
                        ))}
                    </div>

                    <div className="mt-12">
                        <h3 className="hidden md:block text-[10px] font-bold text-gray-600 uppercase tracking-widest mb-4 px-2">{t.layers}</h3>
                        <div className="space-y-2">
                            {elements.map(el => (
                                <div
                                    key={el.id}
                                    onClick={() => setSelectedId(el.id)}
                                    className={cn(
                                        "flex items-center gap-3 px-3 py-2 rounded-xl text-xs cursor-pointer transition-all",
                                        selectedId === el.id ? "bg-purple-500/10 text-purple-400 border border-purple-500/20" : "text-gray-500 hover:bg-white/5 hover:text-white"
                                    )}
                                >
                                    <Layers size={14} />
                                    <span className="hidden md:block">{el.label}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                </aside>

                {/* Center: Canvas */}
                <main className="flex-1 flex flex-col bg-black relative p-8 items-center justify-start overflow-y-auto">
                    <div
                        className={cn(
                            "bg-[#0A0A0B] border border-white/5 rounded-[40px] shadow-3xl transition-all duration-500 min-h-[600px] p-12 space-y-8 flex flex-col",
                            previewMode === 'desktop' ? "w-full max-w-4xl" : previewMode === 'tablet' ? "w-[600px]" : "w-[360px]"
                        )}
                    >
                        {elements.length === 0 ? (
                            <div className="flex-1 flex flex-col items-center justify-center text-center opacity-20 border-2 border-dashed border-white/10 rounded-[32px]">
                                <MousePointer2 className="mb-4" />
                                <p className="text-sm font-bold uppercase tracking-widest">{t.emptyCanvas}</p>
                                <p className="text-xs">{t.selectComponent}</p>
                            </div>
                        ) : (
                            elements.map((el) => (
                                <div
                                    key={el.id}
                                    onClick={(e) => { e.stopPropagation(); setSelectedId(el.id); }}
                                    className={cn(
                                        "relative transition-all",
                                        selectedId === el.id ? "ring-2 ring-purple-500/50 rounded-xl" : ""
                                    )}
                                >
                                    {el.type === 'button' && (
                                        <button className="px-6 py-2 bg-purple-600 text-white rounded-xl font-bold shadow-lg shadow-purple-500/20 active:scale-95 transition-all">
                                            {el.label}
                                        </button>
                                    )}
                                    {el.type === 'input' && (
                                        <input className="w-full bg-[#161618] border border-white/10 rounded-xl px-4 py-2 focus:border-purple-500 outline-none transition-all" placeholder={el.label + "..."} />
                                    )}
                                    {el.type === 'card' && (
                                        <div className="bg-[#161618] p-6 rounded-3xl border border-white/5 shadow-xl">
                                            <div className="w-12 h-1 w-full bg-white/5 rounded-full mb-4" />
                                            <h3 className="font-bold mb-2 text-lg">{el.label}</h3>
                                            <p className="text-sm text-gray-500 leading-relaxed">{lang === 'en' ? 'Generated container.' : 'Conteneur généré.'}</p>
                                        </div>
                                    )}
                                    {el.type === 'text' && (
                                        <p className="text-gray-400 text-sm leading-relaxed">{el.label}</p>
                                    )}

                                    {selectedId === el.id && (
                                        <button
                                            type="button"
                                            onClick={() => { setElements(elements.filter(e => e.id !== el.id)); setSelectedId(null); }}
                                            className="absolute -right-2 -top-2 w-6 h-6 bg-rose-600 hover:bg-rose-700 rounded-full flex items-center justify-center border-2 border-black transition-all shadow-lg"
                                            title="Delete element"
                                        >
                                            <Trash2 size={10} className="text-white" />
                                        </button>
                                    )}
                                </div>
                            ))
                        )}
                    </div>

                    <div className="mt-8 flex items-center gap-2 text-gray-600 text-[10px] font-black tracking-widest uppercase">
                        <Eye size={12} />
                        {t.realTime}
                    </div>
                </main>

                {/* Right Sidebar: Code & Properties */}
                <aside className="hidden xl:flex w-80 flex-col bg-[#0D0D0F] border-l border-white/5">
                    <div className="flex-1 flex flex-col overflow-hidden">
                        <div className="p-4 border-b border-white/5 bg-[#111113] flex items-center gap-2">
                            <Terminal size={16} className="text-gray-400" />
                            <span className="text-[10px] font-bold uppercase tracking-widest">{t.generatedCode}</span>
                        </div>
                        <div className="flex-1 p-4 bg-black overflow-hidden relative group">
                            <pre className="text-[11px] font-mono text-gray-400 leading-normal h-full overflow-y-auto custom-scrollbar">
                                <code>{generateCode()}</code>
                            </pre>
                            <div className="absolute inset-0 bg-gradient-to-t from-black to-transparent pointer-events-none h-20 top-auto" />
                        </div>
                    </div>

                    <div className="p-6 bg-[#111113] border-t border-white/5">
                        <div className="flex items-center gap-2 mb-4">
                            <Settings2 size={16} className="text-gray-400" />
                            <span className="text-[10px] font-bold uppercase tracking-widest text-white">{t.properties}</span>
                        </div>

                        {selectedId ? (
                            <div className="space-y-4">
                                <div className="space-y-2">
                                    <label className="text-[10px] text-gray-500 uppercase font-black">{t.labelText}</label>
                                    <input
                                        type="text"
                                        title={t.labelText}
                                        value={elements.find(e => e.id === selectedId)?.label || ''}
                                        onChange={(e) => {
                                            setElements(elements.map(el => el.id === selectedId ? { ...el, label: e.target.value } : el));
                                        }}
                                        className="w-full bg-white/5 border border-white/10 rounded-xl px-3 py-2 text-xs focus:border-purple-500 outline-none transition-all"
                                    />
                                </div>
                                <div className="p-4 bg-purple-500/5 rounded-2xl border border-purple-500/10 text-center">
                                    <p className="text-[10px] text-purple-400 font-bold leading-relaxed tracking-tighter">{t.instantFeedback}</p>
                                </div>
                            </div>
                        ) : (
                            <p className="text-xs text-center py-8 text-gray-600">{t.selectToEdit}</p>
                        )}
                    </div>
                </aside>
            </div>
        </div>
    );
}
